apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-sa-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: monitor-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: monitor-sa-cluster-role
  apiGroup: rbac.authorization.k8s.io

