apiVersion: v1
kind: Namespace
metadata:
  name: akash1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ssh
data:
  color: blue 
  SSH: nothing
  code: some 

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
   app: configmap
spec:
  containers:
  - name: myapp-container
    image: nginx
    envFrom:
    - configMapRef:
        name: configmap-ssh