apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydset
  namespace: cool
  labels:
    color: red 
spec:
  selector:
    matchLabels:
      name: mydset2
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2   
  template:
    metadata:
      labels:
        name: mydset2
    spec:    
      containers:
      - name: jpod
        image: httpd
