apiVersion: v1
kind: Pod
metadata:
  name: akapp
  labels:
    name: akapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html/
        name: my1pvc
  volumes:
    - name: my1pvc
      persistentVolumeClaim:
        claimName: mypvc