apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 10
  selector:
    word: coffee
  template:
    metadata:
      name: myapp
      labels:
        word: coffee
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
